movies["DIARY"] = new movie(
	{"1st": 0, "2nd": 4, "3rd": 8, "4th": 12, "5th": 16, "6th": 20, "7th": 24, "8th": 28, "9th": 32, "10th": 36, "11th": 40, "12th": 44, "13th": 48, "14th": 52, "15th": 56, "16th": 60, "17th": 64, "18th": 68, "19th": 72, "20th": 76, "21st": 80},
	[
		{item: load_html('<div style="width: 511px; height: 234px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY</span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; "><br/><br/>Thurs 28/3<br/><br/>I lie in bed & think I could just reach over & pick up my blade & cut a long cut down from the wrist to the inside of the elbow and feel the blood rush relief like heroin vomit, like lying down after a hard day, like the stripjoint after an art dinner. The hatred washes out with the life . <br/>I can feel the dizzy euphoria nausea of blood loss & drift off to blackness & peace after the sick spots in the vision pass and die softly die blood on the white linen sheets. But I don\'t.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 234px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY</span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; "><br/><br/>Sun 31/3<br/><br/>Read Lyotard & watch TV. I think I could swallow all the anti- depressants in the cupboard and would it kill me? I don\'t know what pills can kill. I remember once I  took 19 phenobarbs and scotch and it didn\'t even touch the sides and the three days unconscious after barbiturates and retching in the bath at some stage. <br/>I read Anna Kavan & listen to the prisoners request show. J plays Isaac Hayes for me and I am happy for those minutes.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 126px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY</span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; "><br/><br/>Thurs 4/4<br/><br/>Drink scotch with E & Z & watch videos. The mildness of my life revolts me unless I have a machine in front of me.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 180px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY</span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; "><br/><br/>Mon 8/4<br/><br/>I can\'t work. Why can\'t I work? It is the thing that saves me that makes me live and I am incapable. <br/>A razor cut to the forearm might let it out as if it is the skin that binds me. A cut, a mouth to speak, red to paint, new flesh exposed. Sounds like art to me.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 162px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY</span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; "><br/><br/>Wed 1/1<br/><br/>Fuelled by unreason. I cough green slime & wonder if I will ever finish writing & this art shit or if I will die with the next depression. I wish I could live with this. I wish I could revell in my hate & grief with every move. I wish I had a manual for my flight simulator.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 144px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY</span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; "><br/><br/>Sat 4/1<br/><br/>Antibiotics for the green slime. My dreams are violent and torturous and sleep is not restful. I am tired and sleep is not restful. I am tired and I am not allowed to die.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 126px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY</span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; "><br/><br/>Sun 26/1<br/><br/>I need more than reason and comfort. There must be more than reason and comfort.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 108px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Thurs 7/2<br/><br/>Too horrific<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 162px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Sat 6/3<br/><br/>G is dead again. The days around his death re-run. On the train to work I am sitting with the corpse. Teaching class in the afternoon I am half dead in a Chippendale gutter and his body has gone.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 252px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Tues 7/5<br/><br/>Can\'t go to work. The feelings I feel that are love and desire are grief and amputation. I miss the one I love already. The separation comes with the meeting. It kills me. I know they will die soon. All my friends die. That\'s the way it goes.<br/>This one that makes me feel so who is breath & touch & warmth to me and whom I know will die soon is the ones who are dead already who once were this one breath and warmth and touch and soon to die.<br/>And this is not true. They aren\'t really all dead.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 126px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Mon 31/12<br/><br/>Stagnant. Hot. Can\'t think or wake or move too well. Hundreds of blowflies. Maybe someone is dead downstairs.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 512px; height: 162px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Thurs 2/5<br/><br/>Coffee with L & L. I hate chatting. I am a social autistic. The lesbian scene makes me feel nauseous. Go to the Cross alone & do the rounds. This gives me some peace. My hair smells of cigarettes.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 144px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Fri 17/5<br/><br/>Dinner with T. Sleep in someone else\'s bed is always better. Absent from my own life I stay awake for hours. I wish I still smoked.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 511px; height: 144px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Sat 18/5<br/><br/>Waking up in someone else\'s bed is always better. Absent from my own life before I open my eyes. Black coffee overlooking the garden.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 216px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Mon 5/8<br/><br/>I\'m glad I\'m not Haitian. Why can\'t I work I can\'t work I do no art nothing.<br/><br/>Take her someplace and keep her away from the guns and knives and junk. Take her someplace away from these things and watch her<br/>do nothing.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 180px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Wed 7/8<br/><br/>Hear Janis Joplin on the radio and I want to be back at age 16 stoned and dancing. At peace in the dark with too much sound to think and gone baby gone I danced all night.<br/>I set the mandlebrot off and it takes 10 pop songs on the radio to fill the screen. <br/> </span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 126px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Tues 3/9<br/><br/>If I watch TV without reading at the same time I start to cry. I am needing more and more distraction to block the misery.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 144px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Wed 27/11<br/><br/>Opening. All the right art names kiss me on the cheek. I hate openings I don\'t know how to behave. I start to kick things and speak in monosyllables and swear like a delinquent.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 108px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Mon 2/12<br/><br/>I wish I could work overnight alone and communicate via notes.<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 162px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Sat 7/12<br/><br/>Sleep in. Finish the spy thriller in bed then in the sun at the laundromat. Vacuum the fucking floor and think about what I have to buy at the fucking supermarket. How many times do I have to buy toilet paper?<br/></span></div>'), script: (x) => {/**/}},
		{item: load_html('<div style="width: 513px; height: 198px; text-align: left"><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica;  font-weight: bold;">DIARY<br/><br/></span><span style="color: #000000; font-size: 18px; line-height: 18px; font-family: Helvetica; ">Sun 8/12<br/><br/>Tomorrow I will go to work. The day after that I will do whatever is in my diary to do. The scream inside will scream. The frustration and incapacity will sit and fester beside my constant battle for the reason and comfort I hate. I will eat too much or too little. I will want to smoke and want to hit up and want to cut my flesh and I won\'t. <br/></span></div>'), script: (x) => {/**/}},
		{item: null, script: (x) => {/**/}},
		{item: null, script: (x) => {/**/}},
		{
			item: load_html('<div style="background: #dddddd; width: 661px; height: 498px;"></div>"') /* RECT */,
			script: (x) => {x.onmouseup = (ev) => {load_movie("GLOTTIS", "bend")}}},
		null, // global script
		{item: (mv) => {load_movie("LUNGS")}, script: (x) => {}},
		{item: (mv) => {mv.delay += 640}, script: (x) => {}},
		{item: (mv) => {load_movie("ARM")}, script: (x) => {}},
		{item: (mv) => {load_movie("SCAR")}, script: (x) => {}},
		{item: (mv) => {mv.delay += 520}, script: (x) => {}},
		{item: (mv) => {mv.delay += 720}, script: (x) => {}},
		{item: (mv) => {mv.delay += 400}, script: (x) => {}},
		{item: (mv) => {load_movie("TESTES")}, script: (x) => {}},
		{item: (mv) => {load_movie("HANDS")}, script: (x) => {}},
		{item: (mv) => {load_movie("GLOTTIS")}, script: (x) => {}},
		{item: (mv) => {load_movie("ORGANS")}, script: (x) => {}},
		{item: (mv) => {load_movie("SCAR", "words")}, script: (x) => {}},
		{item: (mv) => {load_movie("TITS")}, script: (x) => {}},
		{item: (mv) => {load_movie("PENES", "words")}, script: (x) => {}},
		{item: (mv) => {mv.goto("14th")}, script: (x) => {}},
		{item: (mv) => {load_movie("HANDS", "words")}, script: (x) => {}},
		{item: (mv) => {load_movie("WOUND")}, script: (x) => {}},
		{item: (mv) => {load_movie("WOUND", "words")}, script: (x) => {}},
	],
	[
		(mv) => {
			mv.onStartMovie = (mv) => {
				mv.timeoutLength = 120*60; // 2min
				mv.onTimeout = (mv) => {
					load_movie("TITS", "timeout sequence");
				};
			};
		}
	],
	[
{"sounds":[null,null],"script":30,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":0,"x":41,"y":118}]},
{"sounds":[null,null],"script":27,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":0,"x":41,"y":118}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":30,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":1,"x":56,"y":91}]},
{"sounds":[null,null],"script":28,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":1,"x":56,"y":91}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":26,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":2,"x":63,"y":131}]},
{"sounds":[null,null],"script":32,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":2,"x":63,"y":131}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":26,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":3,"x":61,"y":106}]},
{"sounds":[null,null],"script":27,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":3,"x":61,"y":106}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":30,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":4,"x":58,"y":123}]},
{"sounds":[null,null],"script":33,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":4,"x":58,"y":123}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":31,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":5,"x":64,"y":135}]},
{"sounds":[null,null],"script":34,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":5,"x":64,"y":135}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":26,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":6,"x":61,"y":140}]},
{"sounds":[null,null],"script":35,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":6,"x":61,"y":140}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":26,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":7,"x":64,"y":126}]},
{"sounds":[null,null],"script":36,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":7,"x":64,"y":126}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":26,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":8,"x":63,"y":119}]},
{"sounds":[null,null],"script":25,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":8,"x":63,"y":119}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":30,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":9,"x":67,"y":90}]},
{"sounds":[null,null],"script":37,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":9,"x":67,"y":90}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":31,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":10,"x":61,"y":119}]},
{"sounds":[null,null],"script":38,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":10,"x":61,"y":119}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":29,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":11,"x":60,"y":131}]},
{"sounds":[null,null],"script":33,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":11,"x":60,"y":131}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":31,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":12,"x":58,"y":142}]},
{"sounds":[null,null],"script":39,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":12,"x":58,"y":142}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":31,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":13,"x":63,"y":124}]},
{"sounds":[null,null],"script":35,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":13,"x":63,"y":124}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":29,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":14,"x":67,"y":116}]},
{"sounds":[null,null],"script":32,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":14,"x":67,"y":116}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":29,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":15,"x":65,"y":129}]},
{"sounds":[null,null],"script":40,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":15,"x":65,"y":129}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":31,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":16,"x":66,"y":130}]},
{"sounds":[null,null],"script":41,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":16,"x":66,"y":130}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":31,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":17,"x":64,"y":138}]},
{"sounds":[null,null],"script":32,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":17,"x":64,"y":138}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":31,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":18,"x":64,"y":139}]},
{"sounds":[null,null],"script":34,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":18,"x":64,"y":139}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":29,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":19,"x":65,"y":122}]},
{"sounds":[null,null],"script":37,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":19,"x":65,"y":122}]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"sprites":[]},
{"sounds":[null,null],"script":30,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":20,"x":70,"y":108}]},
{"sounds":[null,null],"script":42,"sprites":[{"kind":"shape","index":23,"style":""},{"style":"","kind":"text","index":20,"x":70,"y":108}]},
	]
);
